/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NIM_5200411559;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andbayu
 */
public class SIberkom extends javax.swing.JFrame {
    
    DefaultTableModel model;

    /**
     * Creates new form SIberkom
     */
    public SIberkom() {
        initComponents();
        model = (DefaultTableModel) tblSiberkom.getModel();
        tblSiberkom.setModel(model);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgJenis = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSiberkom = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        txtJumlahu = new javax.swing.JTextField();
        cmbSupplier = new javax.swing.JComboBox<>();
        txtNamab = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbPenerima = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdImpor = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaCatatan = new javax.swing.JTextArea();
        rdLokal = new javax.swing.JRadioButton();
        txtHargap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBulan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIBERKOM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setText("Update");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        tblSiberkom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Produk", "Jumlah Unit", "Jenis Produk", "Penerima", "Supplier", "Harga Perunit", "Catatan", "Tanggal"
            }
        ));
        tblSiberkom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSiberkomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSiberkom);

        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setText("ID Terisi Otomatis");
        txtId.setEnabled(false);

        btnClear.setText("Bersihkan");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".: Pilih Supplier :.", "Pusat", "Cabang Semarang", "Cabang Surabaya", "Cabang Jakarta", "Cabang Yogyakarta" }));

        jLabel2.setText("ID");

        jLabel3.setText("Jumlah Unit");

        jLabel4.setText("Nama Barang");

        jLabel5.setText("Supplier");

        cmbPenerima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".: Pilih Penerima :.", "Cabang Semarang", "Cabang Surabaya", "Cabang Jakarta", "Cabang Yogyakarta" }));

        jLabel6.setText("Penerima");

        jLabel7.setText("Jenis Produk");

        rdgJenis.add(rdImpor);
        rdImpor.setText("Impor");

        jLabel8.setText("Catatan");

        txaCatatan.setColumns(20);
        txaCatatan.setRows(5);
        jScrollPane2.setViewportView(txaCatatan);

        rdgJenis.add(rdLokal);
        rdLokal.setText("Lokal");

        jLabel9.setText("Harga Per Unit");

        jLabel10.setText("Bulan");

        jLabel11.setText("Tanggal");

        jLabel12.setText("Tahun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtJumlahu)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(cmbPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtHargap, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel3))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2)
                                        .addGap(102, 102, 102)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtNamab, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(rdLokal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdImpor)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdLokal)
                    .addComponent(rdImpor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJumlahu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHargap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKeluar)
                        .addGap(99, 99, 99)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bersihkan() {
        txtId.setText("ID Terisi otomatis");
        txtNamab.setText("");
        txtJumlahu.setText("");
        rdgJenis.clearSelection();
        cmbPenerima.setSelectedIndex(0);
        cmbSupplier.setSelectedIndex(0);
        txtHargap.setText("");
        txaCatatan.setText("");
        txtTanggal.setText("");
        txtBulan.setText("");
        txtTahun.setText("");
    }
    
    
    private void loadTable() {
        model.setRowCount(0);
        try {
            Connection conn = Koneksi.getKoneksi();
            String sql = "SELECT * FROM siberkom";
            Statement st = conn.createStatement();
            ResultSet res = st.executeQuery(sql);
            
            while (res.next()) {                
                Object[] object = new Object[9];
                object[0] = res.getInt("id");
                object[1] = res.getString("nama_barang");
                object[2] = res.getInt("jumlah_unit");
                object[3] = res.getString("jenis_produk");
                object[4] = res.getString("penerima");
                object[5] = res.getString("supplier");
                object[6] = res.getInt("harga_perunit");
                object[7] = res.getString("catatan");
                object[8] = res.getString("tanggal");
                model.addRow(object);
            }
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi Masalah : "+e);
        }
    }
    
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {

            Connection conn         = Koneksi.getKoneksi();
            String sql              = "INSERT INTO siberkom (nama_barang, jumlah_unit, jenis_produk, penerima, supplier, harga_perunit, catatan, tanggal)"+
                                      " VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps    = conn.prepareStatement(sql);

            String selectedRadio    = "";

            if (rdLokal.isSelected()) {
                selectedRadio = "lokal";
            } else if (rdImpor.isSelected()) {
                selectedRadio = "impor";
            }             

            ps.setString(1, txtNamab.getText());
            ps.setInt(2, Integer.parseInt(txtJumlahu.getText()));
            ps.setString(3, selectedRadio);
            ps.setString(4, cmbPenerima.getSelectedItem().toString());
            ps.setString(5, cmbSupplier.getSelectedItem().toString());
            ps.setInt(6, Integer.parseInt(txtHargap.getText()));
            ps.setString(7, txaCatatan.getText());
            ps.setString(8, txtTahun.getText()+"-"+txtBulan.getText()+"-"+txtTanggal.getText());

            int insertedRow = ps.executeUpdate();

            loadTable();
            if (insertedRow > 0) {
                JOptionPane.showMessageDialog(this, "Berhasil menyimpan data");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
            }
            bersihkan();

        } catch (SQLException e) {
            System.out.println("Terjadi masalah : " + e);
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {

            Connection conn         = Koneksi.getKoneksi();
            String sql              = "UPDATE siberkom SET "+
                                      "nama_barang = ?, "+
                                      "jumlah_unit = ?, "+
                                      "jenis_produk = ?, "+
                                      "penerima = ?, "+
                                      "supplier = ? , "+
                                      "harga_perunit = ?, "+
                                      "catatan = ?, "+
                                      "tanggal = ?  "+
                                      "WHERE id = ?";
            PreparedStatement ps    = conn.prepareStatement(sql);

            String selectedRadio    = "";

            if (rdLokal.isSelected()) {
                selectedRadio = "lokal";
            } else if (rdImpor.isSelected()) {
                selectedRadio = "impor";
            } 

            ps.setString(1, txtNamab.getText());
            ps.setInt(2, Integer.parseInt(txtJumlahu.getText()));
            ps.setString(3, selectedRadio);
            ps.setString(4, cmbPenerima.getSelectedItem().toString());
            ps.setString(5, cmbSupplier.getSelectedItem().toString());
            ps.setInt(6, Integer.parseInt(txtHargap.getText()));
            ps.setString(7, txaCatatan.getText());
            ps.setString(8, txtTahun.getText()+"-"+txtBulan.getText()+"-"+txtTanggal.getText());
            ps.setInt(9, Integer.parseInt(txtId.getText()));

            int insertedRow = ps.executeUpdate();

            loadTable();
            if (insertedRow > 0) {
                JOptionPane.showMessageDialog(this, "Berhasil mengubah data");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data");
            }
            bersihkan();

        } catch (SQLException e) {
            System.out.println("Terjadi masalah : " + e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblSiberkomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSiberkomMouseClicked
        // TODO add your handling code here:
        int getSelectedRow   = tblSiberkom.getSelectedRow();
        String id            =  getFromTable(getSelectedRow, 0).toString();
        String namab         = getFromTable(getSelectedRow, 1).toString();
        String unit          = getFromTable(getSelectedRow, 2).toString();
        String jenis         = getFromTable(getSelectedRow, 3).toString();
        String penerima      = getFromTable(getSelectedRow, 4).toString();
        String supplier      = getFromTable(getSelectedRow, 5).toString();
        String hargaPerunit  = getFromTable(getSelectedRow, 6).toString();
        String catatan       = getFromTable(getSelectedRow, 7).toString();
        String tanggal       = getFromTable(getSelectedRow, 8).toString();
        
        // split tanggal
        String[] splitTanggal = tanggal.split("-");
        
        txtId.setText(id);
        txtNamab.setText(namab);
        txtJumlahu.setText(unit);
        if (jenis.equals("lokal")) rdLokal.setSelected(true); else rdImpor.setSelected(true);
        cmbPenerima.setSelectedItem(penerima);
        cmbSupplier.setSelectedItem(supplier);
        txtHargap.setText(hargaPerunit);
        txaCatatan.setText(catatan);
        txtTanggal.setText(splitTanggal[2]);
        txtBulan.setText(splitTanggal[1]);
        txtTahun.setText(splitTanggal[0]);

        btnSimpan.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);

    }//GEN-LAST:event_tblSiberkomMouseClicked

    private Object getFromTable(int getSelectedRow, int numberOfColumn) {
        return tblSiberkom.getModel().getValueAt(getSelectedRow, numberOfColumn);
    }
    
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            int confirm = JOptionPane.showConfirmDialog(this,"Yakin akan menghapus data ? ",
                "Peringatan !!!",
                JOptionPane.YES_NO_OPTION);

            if (confirm == 0 ) {
                Connection conn         = Koneksi.getKoneksi();
                String sql              = "DELETE FROM siberkom WHERE id = ?";
                PreparedStatement ps    = conn.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(txtId.getText()));
                
                int insertedRow = ps.executeUpdate();
                
                ps.close();
                
                loadTable();
                if (insertedRow > 0) {
                    JOptionPane.showMessageDialog(this, "Berhasil menyimpan data");
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
                }

            }
            bersihkan();

        } catch (SQLException e) {
            System.out.println("Terjadi Masalah : " + e);
        } 
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        bersihkan();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SIberkom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SIberkom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SIberkom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SIberkom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SIberkom().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbPenerima;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdImpor;
    private javax.swing.JRadioButton rdLokal;
    private javax.swing.ButtonGroup rdgJenis;
    private javax.swing.JTable tblSiberkom;
    private javax.swing.JTextArea txaCatatan;
    private javax.swing.JTextField txtBulan;
    private javax.swing.JTextField txtHargap;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJumlahu;
    private javax.swing.JTextField txtNamab;
    private javax.swing.JTextField txtTahun;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
